version: '3.8'

services:
  # MySQL 서비스 정의
  saegil-db:
    image: mysql:8.0
    container_name: saegil-db
    environment:
      MYSQL_ROOT_PASSWORD: 1868
      MYSQL_DATABASE: saegil
    ports:
      - "3307:3306"  # MySQL 포트 매핑
    networks:
      - saegil-network
    volumes:
      - saegil-db-data:/var/lib/mysql

  # Spring Boot 애플리케이션
  recipedemo:
    build:
      context: .  # 현재 디렉토리에서 빌드
    container_name: recipeapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://saegil-db:3307/saegil
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1868
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JWT_SECRET: saegil12345
    ports:
      - "8081:8080"  # Spring Boot 앱 포트 매핑
    depends_on:
      - saegil-db
    networks:
      - saegil-network

networks:
  saegil-network:
    driver: bridge

volumes:
  saegil-db-data: